db:
  image: mongo:latest
  volumes:
    - /home/ubuntu/precipViz/db:/data/db
  command: --smallfiles
  ports:
    - "27017:27017"
load:
  build: py/.
  ports:
    - "5000:5000"
  volumes:
    - /home/ubuntu/precipViz/docker-locker/py/work:/work
  links:
    - db
  stdin_open: true
  tty: true
  #command: python load_data.py 2012
  command: tail -f /dev/null 
  entrypoint: sh -c

node:
  build: node/.
  ports:
    - "8888:8888"
  links:
    - db
  command:
      tail -f /dev/null
      #node mongo_tools.js

